import type { AssetRecord } from '@/domain/assets/types';

// Emits src/domain/assets/manifest.generated.ts. `as const` is what turns the
// keys into the AssetId union, so a typo in an asset id is a compile error.
export function renderManifest(records: ReadonlyArray<AssetRecord>): string {
  const entries = records
    .map((r) => {
      const lines = [
        `    id: '${r.id}',`,
        `    label: ${JSON.stringify(r.label)},`,
        `    url: '${r.url}',`,
        `    bytes: ${r.bytes},`,
        `    triangles: ${r.triangles},`,
        `    category: '${r.category}',`,
        `    footprint: [${r.footprint[0]}, ${r.footprint[1]}],`,
        `    priceFocus: ${r.priceFocus},`,
        `    priceInsight: ${r.priceInsight},`,
        `    rarity: '${r.rarity}',`,
        `    minLevel: ${r.minLevel},`,
        ...(r.wind
          ? [
              `    wind: { amplitude: ${r.wind.amplitude}, speed: ${r.wind.speed} },`,
            ]
          : []),
      ];
      return `  ${r.id}: {\n${lines.join('\n')}\n  },`;
    })
    .join('\n');

  return [
    '// Generated by `pnpm assets:optimize`. Do not edit by hand.',
    "import type { AssetRecord } from './types';",
    '',
    'export const ASSET_MANIFEST = {',
    entries,
    '} as const satisfies Record<string, AssetRecord>;',
    '',
    'export type AssetId = keyof typeof ASSET_MANIFEST;',
    '',
    'export const ASSET_IDS = Object.keys(ASSET_MANIFEST) as AssetId[];',
    '',
    'export function isAssetId(value: string): value is AssetId {',
    '  return Object.prototype.hasOwnProperty.call(ASSET_MANIFEST, value);',
    '}',
    '',
  ].join('\n');
}
